In [ ]:
#  Array Creation Functions
# 1]  BASIC :

In [1]:
#  list into ndarray
#  1)
import numpy as np

a = np.array([1,2,0],dtype=float)


print(a)

[1. 2. 0.]


In [2]:
# 2) zeros and ones 
c=np.zeros((3,3))
d=np.ones((4,2))
print("zeros",c)
print("ones",d)



zeros [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
# 3) np.full()
n=3
m=2
d=np.full((n,m), 47)  # fills n x m array with 7

print(d)

[[47 47]
 [47 47]
 [47 47]]


In [4]:
# 4) np.eye()
e=np.eye(3)  # 3x3 identity matrix
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 5) np.empty()
f=np.empty((2,3))
print(f)


[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [16]:
# 2] Range 

# 1) np.arange()  act like range() function 
x=np.arange(0, 10, 2)
print(x)
y=np.arange(5)     
print(y)


[0 2 4 6 8]
[0 1 2 3 4]


In [ ]:
x=np.linspace(500,1000,5)     # (b-a)/n-1
print(x)

[ 500.  625.  750.  875. 1000.]


In [9]:
t=np.logspace(1, 3, 4)  
print(t)

[  10.           46.41588834  215.443469   1000.        ]


In [ ]:
# 3] Random 
# 1) np.random.rand()   
arr=np.random.rand(3,3)    # generate random num between 0-1 float 
print(arr)

[[0.93301226 0.21411283 0.81792576]
 [0.41999108 0.29803852 0.26911574]
 [0.72429081 0.42263288 0.37036606]]


In [ ]:
# 2) 
ab=np.random.randn(2,2)
print(ab)

[[-1.04887031  1.2100243 ]
 [-0.57006908  0.28586082]]


In [ ]:
# 3)
p=np.random.randint(0,10,(3,3))
print(p)
q=np.random.randint(99)   # one num as parameter means [0,n) and one element 
print(q)

[[3 4 4]
 [3 0 7]
 [7 2 0]]
81


In [ ]:
# 4)
np.random.seed(42)
#  random ness become constant , and argument is any nums u put 
a = np.random.rand(4)      
b = np.random.rand(2, 4)   

print(a)  
print(b)  


[0.37454012 0.95071431 0.73199394 0.59865848]
[[0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
result = np.random.choice(arr, 3)
print(result)     


[50 30 40]


In [ ]:
# 5) np.random.shuffle() --> operate on mutabilities 
v=[9,23,44,65,87,92]
print(v)
np.random.shuffle(v)
print(v)

[9, 23, 44, 65, 87, 92]
[23, 92, 44, 9, 87, 65]
