## (n,) & (n,1) & (1,n) Array 
##  1d     2d      2d

In [1]:
#  pure 1d matrics 
import numpy as np
a=np.array([1,2,3])
print(a)
print("Shape",a.shape)
# 2d matrics 
a=np.array([[1,2,3]])
print(a)
print("Shape",a.shape)

a=np.array([[1],[2],[3]])
print(a)
print("Shape",a.shape)

import numpy as np

# Creating a mock dataset with 3 samples and 2 features
data = np.array([[10, 0.5], 
                 [15, 0.7], 
                 [12, 0.2]])

# Check the shape
samples, features = data.shape

print(f"Number of samples (rows): {samples}")    # Outputs: 3
print(f"Number of features (columns): {features}") # Outputs: 2


[1 2 3]
Shape (3,)
[[1 2 3]]
Shape (1, 3)
[[1]
 [2]
 [3]]
Shape (3, 1)
Number of samples (rows): 3
Number of features (columns): 2


In [2]:
#  Array Creation Functions
# 1]  BASIC :

In [3]:
#  list into ndarray
#  1)
a = np.array([1,2,0],dtype=float)


print(a)

[1. 2. 0.]


In [4]:
# 2) zeros and ones 
c=np.zeros((3,3))
d=np.ones((4,2))
print("zeros",c)
print("ones",d)



zeros [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# 3) np.full()
n=3
m=2
d=np.full((n,m), 47)  # fills n x m array with 7

print(d)

[[47 47]
 [47 47]
 [47 47]]


In [6]:
# 4) np.eye()
e=np.eye(4,2,3)  # 3x3 identity matrix
print(e)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
# 5) np.empty()
f=np.empty((2,2))
print(f)


[[0.00000000e+000 1.07490026e-311]
 [1.07490026e-311 1.07490026e-311]]


In [8]:
# 2] Range 

# 1) np.arange()  act like range() function 
x=np.arange(0, 10, 2)
print(x)
y=np.arange(5)     
print(y)


[0 2 4 6 8]
[0 1 2 3 4]


In [9]:
x=np.linspace(500,1000,5)     # (b-a)/n-1
print(x)

[ 500.  625.  750.  875. 1000.]


In [10]:
t=np.logspace(1, 3, 4)  
print(t)

[  10.           46.41588834  215.443469   1000.        ]


In [11]:
# 3] Random 
# 1) np.random.rand()   
arr=np.random.rand(3,3)    # generate random num between 0-1 float 
print(arr)

[[0.4789194  0.1835845  0.14704544]
 [0.4516821  0.54327012 0.22383269]
 [0.1966445  0.49293915 0.93699423]]


In [12]:
# 2) 
ab=np.random.randn(2,2)
print(ab)

[[ 1.32667664 -0.53138322]
 [ 0.46662296  0.57118838]]


In [13]:
# 3)
p=np.random.randint(0,10,(3,3))
print(p)
q=np.random.randint(99)   # one num as parameter means [0,n) and one element 
print(q)

[[4 2 5]
 [7 5 0]
 [5 4 3]]
30


In [14]:
# 4)
np.random.seed(42)
#  random ness become constant , and argument is any nums u put 
a = np.random.rand(4)      
b = np.random.rand(2, 4)   

print(a)  
print(b)  


[0.37454012 0.95071431 0.73199394 0.59865848]
[[0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


In [15]:
arr = np.array([10, 20, 30, 40, 50])
result = np.random.choice(arr, 3)
print(result)     


[40 20 40]


In [16]:
# 5) np.random.shuffle() --> operate on mutabilities 
v=[9,23,44,65,87,92]
print(v)
np.random.shuffle(v)
print(v)

[9, 23, 44, 65, 87, 92]
[92, 44, 23, 65, 9, 87]
