```text
Data Matrix
    |
    v
Matrix Operations
    |
    v
Linear Algebra
    |
    v
ML Algorithms
```

## np.linalg.norm()

**Purpose:** Measure the magnitude (length) of a vector or matrix.

Linear Algebra = math of vectors and matrices.

## In Machine Learning, it is used everywhere:

- **Data** → Matrix
- **Features** → Vectors
- **Weights** → Vectors/Matrices
- **Predictions** → Matrix operations

### Types

```python
np.linalg.norm(v)         # L2 Norm (Euclidean)
np.linalg.norm(v, ord=1)  # L1 Norm (Manhattan)
np.linalg.norm(A)         # Frobenius Norm (Matrix)
```

### ML Use

Used for distance calculation, normalization, KNN, PCA, and optimization.

In [2]:
# CORE : 

import numpy as np

v = np.array([3, 4])
print(np.linalg.norm(v))        # 5.0  (Euclidean distance √(9+16))
print(np.linalg.norm(v, ord=1)) # 7.0  (Manhattan: 3+4)

#  it always takes absolute values of elements before summing.
z=np.array([-3,4,5])
print(np.linalg.norm(z))
print(np.linalg.norm(z,ord=1))


# np.linalg.norm() is literally just √(x² + y² + z²).

# Matrix norm
A = np.array([[1,2],
              [3,4]
              ])
print(np.linalg.norm(A))        # Frobenius norm by default
print(np.linalg.norm(A,ord=1,axis=1))     # Sum row wise 


5.0
7.0
7.0710678118654755
12.0
5.477225575051661
[3. 7.]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A ,B))

print(np.linalg.inv(A))
# What it does: Finds inverse of a square matrix.

print(np.linalg.det(B))
# What it does: Calculates determinant of a matrix.

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.000000000000005


In [4]:
# DECOMPOSITION

# What it does: Returns eigenvalues and eigenvectors of a matrix.
# Example:
A = np.array([[2, 0],
              [0, 3]
])
values, vectors = np.linalg.eig(A)
print("Eigen value : ",values)
print("Eigen vectors :\n ",vectors)

B = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])

vals, vecs = np.linalg.eig(B)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)


Eigen value :  [2. 3.]
Eigen vectors :
  [[1. 0.]
 [0. 1.]]
Eigenvalues: [1. 2. 3.]
Eigenvectors:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# SVD Calculation Sheet
## A = U * S * Vt

---

## Given Matrix
```
A = [[1, 2],
     [3, 4],
     [5, 6]]
```

---

## STEP 1 — Calculate S (Singular Values)

### 1.1 Find Aᵀ
```
Aᵀ = [[1, 3, 5],
       [2, 4, 6]]
```

### 1.2 Find AᵀA
```
AᵀA = Aᵀ * A = [[35, 44],
                  [44, 56]]
```

### 1.3 Find Eigenvalues of AᵀA
```
eigenvalues = [90.66, 0.26]
```

### 1.4 Take Square Root → S
```
S = [√90.66, √0.26]
S = [9.52,   0.51]
```

---

## STEP 2 — Calculate Vt (Right Singular Vectors)

### 2.1 Find Eigenvectors of AᵀA → V
```
V = [[-0.619, -0.785],
     [-0.785,  0.619]]
```

### 2.2 Transpose V → Vt
```
Vt = [[-0.619, -0.785],
      [-0.785,  0.619]]
```

---

## STEP 3 — Calculate U (Left Singular Vectors)

### 3.1 Find AAᵀ
```
AAᵀ = A * Aᵀ = [[ 5, 11, 17],
                  [11, 25, 39],
                  [17, 39, 61]]
```

### 3.2 Find Eigenvectors of AAᵀ → U
```
U = [[-0.229,  0.883],
     [-0.524,  0.240],
     [-0.819, -0.403]]
```

---

## STEP 4 — Reconstruct A = U * S_matrix * Vt

### 4.1 Make S_matrix (3x2) from S
```
S_matrix = [[9.52, 0.00],
             [0.00, 0.51],
             [0.00, 0.00]]
```

### 4.2 Multiply
```
A = U * S_matrix * Vt
A = [[1, 2],
     [3, 4],
     [5, 6]]  ✅
```

---

## Flow Summary
```
S  →  eigenvalues  of AᵀA  →  √        →  S
Vt →  eigenvectors of AᵀA  →  transpose →  Vt
U  →  eigenvectors of AAᵀ              →  U
```

---

## Python Code
```python
import numpy as np

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Direct SVD
U, S, Vt = np.linalg.svd(A)

# Reconstruct
S_matrix = np.zeros((3, 2))
np.fill_diagonal(S_matrix, S)
A_reconstructed = U @ S_matrix @ Vt

print(A_reconstructed)  # [[1,2],[3,4],[5,6]] ✅
```


In [5]:
# SVD - Simple Explanation
# Core idea: Break one matrix into 3 simpler matrices.
# A = U * S * Vt

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = np.linalg.svd(A)
print(U)
print(S)
print(Vt)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [6]:
#  np.linalg.qr(a)
# What it does: Splits matrix into Q (orthogonal) and R (upper triangular).
A = np.array([[1, 2], [3, 4], [5, 6]])
Q, R = np.linalg.qr(A)
print(Q)
print(R)

# A (3x2) is split into:

# Q → (3x2) orthogonal matrix
#      [[-0.169,  0.897],
#       [-0.507,  0.276],
#       [-0.845, -0.345]]

# R → (2x2) upper triangular
#      [[-5.916, -7.437],
#       [ 0.   ,  0.828]]

# Relation: A = Q * R

[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [7]:
# np.linalg.solve(A, b)
# What it does: Solves Ax = b → finds x
# Example:
A = np.array([[2, 1],
              [1, 3]])
b = np.array([8, 13])


x = np.linalg.solve(A, b)
print(x)  # [3., 4. - 0.33...]

# Ax = b means:
# 2x + 1y = 8   → equation 1
# 1x + 3y = 13  → equation 2

# solving...
# x = 3.0 (approximately)
# y = 2.0 (approximately)  

# verify: 2(3) + 1(2) = 8 
#         1(3) + 3(2) = 9 

[2.2 3.6]


### np.linalg.lstsq() Outputs

| Output | What it means | How to find it |
|----------|----------|----------|
| `x` | Best-fit solution (weights) | Solves `Ax ≈ b` |
| `residuals` | Total fitting error | `Σ(actual - predicted)²` |
| `rank` | Number of independent columns | Count columns that cannot be made from other columns |
| `s` | Singular values | Computed from SVD (`A = UΣVᵀ`) |

### Quick Example

A =
[[1,1],
 [1,2],
 [1,3]]

b = [2,3,5]

- `x = [0.3333, 1.5]` → best-fit weights
- `residuals = 0.1667` → total squared error
- `rank = 2` → both columns are independent
- `s = [4.08, 0.60]` → singular values of `A`

### Memory Trick

- `x` → Solution
- `residuals` → Error
- `rank` → Independence
- `s` → Strength

In [11]:
# np.linalg.lstsq(A, b)
# What it does: Solves Ax = b when no exact solution exists → finds best approximate x
# Example:
A = np.array([[1, 1],
              [1, 2],
              [1, 3]])
b = np.array([2, 3, 5])

x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print(x)
print(residuals)
print(rank)
print(s)
# Dry Run:
# 3 equations, 2 unknowns → over-determined
# no exact solution exists

# lstsq finds x that minimizes:
# → ||Ax - b||²  (least squares error)

# Condition: Works for any shape matrix (3x2, 4x2 etc.)
b,n,m=np.linalg.svd(A)
print(b)
print(n)
print(m)

[0.33333333 1.5       ]
[0.16666667]
2
[4.07914333 0.60049122]
[[-0.32310986  0.85377594  0.40824829]
 [-0.54750702  0.18321952 -0.81649658]
 [-0.77190419 -0.4873369   0.40824829]]
[4.07914333 0.60049122]
[[-0.40266324 -0.91534819]
 [ 0.91534819 -0.40266324]]


In [12]:
A1 = np.array([[1,2],[2,4]])
A2 = np.array([[1,2],[3,4]])
A3 = np.eye(3)

print(np.linalg.matrix_rank(A1))  # 1
print(np.linalg.matrix_rank(A2))  # 2
print(np.linalg.matrix_rank(A3))  # 3

1
2
3
