In [1]:
# Copying & Memory
import numpy as np
# arr.view()
# What it does: Creates new array object but shares same memory
# Example:
arr = np.array([1, 2, 3, 4])
v = arr.view()

v[0] = 99
print(arr)  # [99,  2,  3,  4]  ← original changed!

[99  2  3  4]


In [2]:
# arr.copy()
# What it does: Creates new array with new memory
# Example:
arr = np.array([1, 2, 3, 4])
c = arr.copy()

c[0] = 99
print(arr)  # [1, 2, 3, 4]  ← original safe!
print(c)    # [99, 2, 3, 4]

[1 2 3 4]
[99  2  3  4]


In [3]:
# arr.base ( bool output  )
# What it does: Tells you who owns the memory
arr = np.array([1, 2, 3, 4])
v = arr.view()
c = arr.copy()

print(v.base is arr)  # True  ← view depends on arr
print(c.base is arr)  # False ← copy is independent

True
False


In [4]:
# MEMORY Functions   
# arr.flags
arr = np.array([1, 2, 3, 4])
print(arr.flags)
# OWNDATA = True   ← owns its memory
v = arr.view()
print(v.flags)
# OWNDATA = False  ← borrowed memory

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [5]:
# np.shares_memory(a, b)
arr = np.array([1, 2, 3])
v = arr.view()
c = arr.copy()

print(np.shares_memory(arr, v) ) # True
print(np.shares_memory(arr, c) ) # False

# np.may_share_memory(a, b)
print(np.may_share_memory(arr, v) ) # True  (quick check)
# Difference:
# shares_memory()     → exact check   → slow
# may_share_memory()  → quick check   → fast (used in large arrays)

True
False
True


In [6]:
#  Vectorization & Performance Important
# VECTORIZE
# np.vectorize() np.frompyfunc() np.apply_along_axis()
# BEST PRACTICE
# avoid Python loops use broadcasting
# instead
# use functions

def sq(x):
    return x*x
x=np.array([4,5,6,6,7,8])
z=np.vectorize(sq)
print(z(x))

# np.vectorize() is still a loop internally
# cleaner code but NOT faster than manual loop
# use it for convenience, not speed

[16 25 36 36 49 64]


In [7]:
# np.frompyfunc(func, nin, nout)
# What it does: Like vectorize but returns object array, lower level
# Example:
def add(x, y):
    return x + y

ufunc_add = np.frompyfunc(add, 2, 1)
#                              ↑  ↑
#                         inputs outputs

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(ufunc_add(arr1, arr2))  # [5, 7, 9]

# nin  = 2 → function takes 2 inputs
# nout = 1 → function gives 1 output

# ufunc_add([1,2,3], [4,5,6])
# → [add(1,4), add(2,5), add(3,6)]
# → [5, 7, 9]

[5 7 9]


In [8]:
# np.apply_along_axis(func, axis, arr)
# What it does: Apply function along row or column
# Example:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.apply_along_axis(np.sum, axis=1, arr=arr)
print(result)  # [6, 15]


[ 6 15]


In [9]:
# BEST PRACTICES
# Avoid Python Loops - slow
arr = np.array([1, 2, 3, 4])
result = []
for x in arr:
    result.append(x * 2)

# CORRECT - fast
result = arr * 2  
print(result)

# Use Broadcasting
# python instead of loop
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# add 10 to every element
# A + 10
# [[11, 12, 13],
#  [14, 15, 16]]    no loop needed

# Use ufuncs

result = [np.sqrt(x) for x in arr]  # loop

# CORRECT
result = np.sqrt(arr)  # ufunc → C speed 
# Common ufuncs:
# np.sqrt()   np.exp()   np.log()
# np.sin()    np.abs()   np.add()
# np.multiply()          np.maximum()



[2 4 6 8]
