# NumPy `clip()` Function

### What it does:
`np.clip(arr, min, max)` limits values in an array:
- Values **below `min`** → replaced with `min`
- Values **above `max`** → replaced with `max`
- Values **within range** → stay unchanged

---

### Example:
```python
import numpy as np

arr = np.array([-3, 0, 2, 5, 10])
print(np.clip(arr, 0, 5))


In [1]:
# ML-Specific Utility Functions
import numpy as np
# CLIPPING & SIGNS
# 1. np.clip(arr, min, max)
# What it does: Cuts values — below min → min, above max → max
# Example:

arr = np.array([-3, 0, 2, 5, 10])
print(np.clip(arr, 0, 5))  # [0, 0, 2, 5, 5]

v=np.array([-10,10,20,30,40,50,60,70,-70])
print(np.clip(v,30,60))

# ML Use: Gradient clipping — prevents exploding gradients

[0 0 2 5 5]
[30 30 30 30 40 50 60 60 30]


In [2]:
# 2. np.sign(arr)
# What it does: Returns -1, 0, or 1 based on sign
# Example:
arr = np.array([-5, 0, 3])
print(np.sign(arr))  # [-1, 0, 1]

brr=np.array([5,-5,0,3,4,-44,1,2,-7])
print(np.sign(brr))
# ML Use: Used in SVM, perceptron decision boundary

# 3. np.abs(arr)
# What it does: Removes negative sign
print(np.abs(arr))
print(np.abs(brr))

# ML Use: L1 loss = np.mean(np.abs(y_pred - y_true))

[-1  0  1]
[ 1 -1  0  1  1 -1  1  1 -1]
[5 0 3]
[ 5  5  0  3  4 44  1  2  7]


# Activation Math in NumPy

### 1. `np.tanh(x)`
- Formula: \(\tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}\)
- Range: (-1, 1)
- Use: Common activation in ML (smooth, bounded).

### 2. `np.sinh(x)`
- Formula: \(\sinh(x) = \frac{e^x - e^{-x}}{2}\)
- Range: (-∞, ∞)
- Use: Hyperbolic sine, grows fast like exponential.

### 3. `np.cosh(x)`
- Formula: \(\cosh(x) = \frac{e^x + e^{-x}}{2}\)
- Range: [1, ∞)
- Use: Hyperbolic cosine, always positive.

---

### Quick Example:
```python
import numpy as np

x = np.array([-1, 0, 1])
print(np.tanh(x))  # [-0.761  0.     0.761]
print(np.sinh(x))  # [-1.175  0.     1.175]
print(np.cosh(x))  # [1.543   1.     1.543]



In [3]:
x = np.array([-1, 0, 1])
print(np.tanh(x))  # [-0.761  0.     0.761]
print(np.sinh(x))  # [-1.175  0.     1.175]
print(np.cosh(x))  # [1.543   1.     1.543]

# np.tanh(arr)
# What it does: Squashes values between -1 and 1
# np.sinh(arr)
# What it does: Hyperbolic sine — output range -∞ to +∞
# np.cosh(arr)
# What it does: Hyperbolic cosine — output always ≥ 1

[-0.76159416  0.          0.76159416]
[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]


# Distribution / Frequency Utilities in NumPy

### 1. `np.histogram()`
- Splits data into bins and counts frequency in each bin.  
- Good for **distribution analysis**.  

In [4]:

# bins = how many parts you want to divide data into

marks = np.array([15, 45, 67, 72, 80, 85, 90, 95])
print(marks.size)
counts, edges = np.histogram(marks, bins=2)
print(counts)
print(edges)
# how to find edges :
# min=15, max=95, range=80          , range = max - min

# 80 / 3 = 26.6 (each bin width)

# edge 0 = 15.0         ← start
# edge 1 = 15 + 26.6 = 41.6
# edge 2 = 41.6 + 26.6 = 68.3
# edge 3 = 95.0         ← end

# edges = [15.0, 41.6, 68.3, 95.0]

# how to find count

# bin 1 (15.0 to 41.6)  → [15]              → count = 1
# bin 2 (41.6 to 68.3)  → [45, 67]          → count = 2
# bin 3 (68.3 to 95.0)  → [72,80,85,90,95]  → count = 5

# counts = [1, 2, 5]

8
[2 6]
[15. 55. 95.]


In [5]:
# bincount()

l=np.array([25,25,50,50,75,75,75])
count=np.bincount(l)
print(count[75])

3


In [6]:
# np.digitize()
marks = np.array([25, 45, 70, 85,36])
bins  = np.array([33, 66, 100])
#                  F   C   B/A

print(np.digitize(marks, bins))

bins = [33, 66, 100]

# creates boundaries:

# zone 0: below 33
# zone 1: 33 to 66
# zone 2: 66 to 100
# zone 3: above 100

# now check each mark:
# 25  < 33        → zone 0 (Fail)
# 45  in 33-66    → zone 1 (C)
# 70  in 66-100   → zone 2 (B)
# 85  in 66-100   → zone 2 (B)
# 36  in 33-45    → zone 1 (C)
# output = [0, 1, 2, 2]

[0 1 2 2 1]


In [7]:
# SET OPERATIONS : Most NumPy set operations work on arrays of any dimension,
#                  but NumPy first flattens them to 1D, and the output is usually 1D.

# These work exactly like Maths sets:
# A = {1,2,3}  B = {2,3,4}

# union        → all elements
# intersection → common elements
# difference   → only in A
# isin         → is this value in set?

A = np.array([1, 2, 3 , 5])
B = np.array([2, 3, 4])

print(np.union1d(A, B))
print(np.intersect1d(A, B))

#  np.setdiff1d(a, b)
# What it does: Elements in A but not in B
# Example:
# A = np.array([1, 2, 3])
# B = np.array([2, 3, 4])

print(np.setdiff1d(A, B))



[1 2 3 4 5]
[2 3]
[1 5]


In [8]:
# np.isin(arr, values)  --> output: bool
# What it does: Check each element — is it in the given list?
# Example:
arr    = np.array([1, 2, 3, 4, 5])
values = np.array([2, 4])

print(np.isin(arr, values))
print(np.isin(arr,5))
# keep only class 2 and 4
print(arr[np.isin(arr, [2, 4])])  # [2, 4]

[False  True False  True False]
[False False False False  True]
[2 4]


- SAVING & LOADING DATA<br>

Core Idea : <br>
**numpy format (.npy)**  → fast, binary, numpy only
**text/csv format**   → slow, readable, shareable

In [ ]:
# NUMPY FORMAT
# np.save(file, arr)
# What it does: Save single array as .npy file
import pandas as pd

arr = np.array([1, 2, 3, 4])
np.save('mydata.npy', arr)

da=np.load("mydata.npy")
print(da)


# np.savez(file, a=arr1, b=arr2)
# What it does: Save multiple arrays in one .npz file
# Example:
X = np.array([1, 2, 3])
y = np.array([0, 1, 0])

np.savez('dataset.npz', X=X, y=y)

# load back
data = np.load('dataset.npz')
print(data['X'])  # [1, 2, 3]
print(data['y'])  # [0, 1, 0]

# np.savez_compressed(file, a=arr1)
# What it does: Same as savez but smaller file size
np.savez_compressed('dataset_small.npz', X=X, y=y)

s=np.load("dataset_small.npz")
print(s["X"])
# savez()            → fast save, normal size
# savez_compressed() → slow save, smaller size

# use compressed when storage matters

# TEXT / CSV FORMAT
#  np.loadtxt(file)
# What it does: Load simple text/csv file
# Example:
# data.csv:
# 1.0  2.0  3.0
# 4.0  5.0  6.0


arr = np.loadtxt('data.csv', delimiter=',')
print(arr)

print(arr)
# [[1. 2. 3.]
#  [4. 5. 6.]]

# np.savetxt(file, arr)
# What it does: Save array as text/csv file
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('data.csv', arr, delimiter=',')


# np.genfromtxt(file)
# What it does: Like loadtxt but handles missing values
arr = np.genfromtxt('data.csv', delimiter=',', filling_values=0)



[1 2 3 4]
[1 2 3]
[0 1 0]
[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
