CH 4
Indexing & Slicing 

In [19]:
import numpy as np
b=np.array([4,5,2,7,8,9,1,0])

print(b[0],b[-8])
print(b[5])

4 4
9


In [20]:
#  slicing 
b=np.array([1,4,5,2,7,9,0,8,8,7,6,2,3,4,5])
print(b.size)
print(b[0:15:2])                       # [start : stop(execluding) : step]

15
[1 5 7 0 8 6 3 5]


In [21]:
# 2d array indexing and slicing 

c=np.array([
    [5,6,45],
    [63,3,4],
    [1,8,5]


])
# how to slice any raw :  arr[raw, :]
print(c[1,:])
# how to slice any cloumn  arr[:, col]
print(c[:,2])
# sub matircs slice  arr[r1:r2, c1:c2]
print(c[0:2,0:2])

[63  3  4]
[45  4  5]
[[ 5  6]
 [63  3]]


In [22]:
o=np.array([
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
],    
[
    [2,8,9],
    [1,7,9],
    [6,7,4],
    [8,2,6]
],
[
    [18,7,56],
    [6,8,0],
    [0,2,5],
    [8,9,0]
]


])

print(o[0,0,0:2])
print(o[0])        # 0th element of 3d array is 1st layer 
print(o[2])        # 1st element of 3d array is 2d layer 
print(o[0,0:2])    # Go through the 0th element(1st) array and raw is act as one element  
print()


[1 7]
[[1 7 9]
 [0 7 4]
 [8 2 6]
 [6 7 4]]
[[18  7 56]
 [ 6  8  0]
 [ 0  2  5]
 [ 8  9  0]]
[[1 7 9]
 [0 7 4]]



Negative indexing in 2D
arr[-1, :] / arr[:, -1]


In [23]:
g=np.array([
    [1,3,5,6],
    [7,8,7,4],
    [5,6,2,1],
    [9,0,1,5]
])
print(g[-1,:])
print(g[-3,:])
print(g[:,-1])
print(g[:,-4])

[9 0 1 5]
[7 8 7 4]
[6 4 1 5]
[1 7 5 9]


3D Array Indexing & Slicing

In [24]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],    # Layer 1

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]], # Layer 2

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]  # Layer 3
])
# arr[layer]
# One full 2D layer 
print(arr[2])
print("Only Layer  : " )
print(arr[2,:,:])
print("Only Row  : " )
print(arr[:,2,:])
print("Only Column  : " )
print(arr[:,:,[2]])

# arr[l, r, c]
# Lth layer ,Rth raw , and Cth column

print(arr[2,1,1])

[[19 20 21]
 [22 23 24]
 [25 26 27]]
Only Layer  : 
[[19 20 21]
 [22 23 24]
 [25 26 27]]
Only Row  : 
[[ 7  8  9]
 [16 17 18]
 [25 26 27]]
Only Column  : 
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]
23


3D CUBE Slicing 
arr[l1:l2, r1:r2, c1:c2]   


In [25]:
print(arr[0:3, 0:2, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


# ⚡ Conditions for Array Operations in NumPy
The core rule before any operation:  
NumPy **checks shapes FIRST**.  
If shapes don't match, it **either broadcasts or throws an error.**

---

## 1. Same Shape
- Arrays must have the **same shape** for direct element‑wise operations.
- Example: `(2,3)` + `(2,3)` → works ✔

---

## 2. Broadcasting Rule
- If shapes differ, NumPy applies **broadcasting**.
- Rule: Compare dimensions **from right to left**.
  - Two dimensions are compatible if:
    - They are **equal**, OR
    - One of them is **1** (can be stretched).
- If all dimensions follow this → operation works ✔  
- If not → ❌ `ValueError`

---

## 3. Scalar with Array
- A single number (scalar) always works with any array.
- Example: `arr + 5` → adds 5 to every element ✔

---

## 4. Incompatible Shapes
- If dimensions are neither equal nor 1 → operation fails.
- Example: `(2,3)` + `(2,)` → ❌ error (last dim 3 vs 2)

---

## All Broadcasting Rules — Final List

- **RULE 1 — Same shape → always works**  
  `(3,)   + (3,)`     ✅  
  `(2,3)  + (2,3)`    ✅  
  `(2,3,4)+ (2,3,4)`  ✅  

- **RULE 2 — Scalar → always works**  
  `(any shape) + single number`  ✅ stretches to entire array  

- **RULE 3 — Missing dimension → treated as 1**  
  `(2,3) + (3,)`  
  ↓  
  `(2,3) + (1,3)` → then Rule 4 applies  
  1D array always becomes a ROW automatically.  

- **RULE 4 — Dimension is 1 → stretches to match**  
  `(2,3) + (1,3)` → row 1 stretches to 2 → `(2,3)` ✅  
  `(2,3) + (2,1)` → col 1 stretches to 3 → `(2,3)` ✅  
  `(3,1) + (1,3)` → both stretch → `(3,3)` ✅  

- **RULE 5 — Neither equal nor 1 → ERROR**  
  `(2,3) + (3,3)` ❌ rows 2 vs 3  
  `(2,3) + (2,4)` ❌ cols 3 vs 4  
  `(2,3) + (4,5)` ❌ both wrong  

- **RULE 6 — 3D with 2D → stretches depth**  
  `(a,b,n) + (b,n)`    ✅ → `(a,b,n)`  
  `(a,b,n) + (1,1,n)`  ✅ → `(a,b,n)`  
  `(a,b,n) + (a,1,n)`  ✅ → `(a,b,n)`  
  `(a,b,n) + (a,b,1)`  ✅ → `(a,b,n)`  

---

# 🔄 Extra Broadcasting Scenarios in NumPy

## 7. Row vs Column Expansion
- `(n,1)` + `(1,n)` → both stretch to `(n,n)` ✔  
- Example: `(3,1)` + `(1,3)` → `(3,3)` matrix

---

## 8. Higher‑Dimensional with Lower‑Dimensional
- If one array has **fewer dimensions**, NumPy prepends `1`s to match.  
- Example: `(4,3,2)` + `(3,2)`  
  → `(4,3,2)` + `(1,3,2)` → works ✔

---

## 9. Chain Broadcasting
- Multiple `1`s can stretch at once.  
- Example: `(2,1,1)` + `(1,3,4)`  
  → `(2,3,4)` final shape ✔

---

## 10. Practical Error Traps
- `(2,3)` + `(3,)` ❌ — last dimension mismatch (3 vs 2)  
- `(4,2,3)` + `(4,3)` ❌ — middle dimension mismatch (2 vs 3)

---

## ✅ Quick Recap
- Always compare **shapes from right to left**.  
- Equal or `1` → compatible.  
- Anything else → ❌ `ValueError`.


In [26]:
n=np.array([2,7,5,22])
r=np.array([1,2,6,3])
x=n+r
k=n-r
y=n+2
z=n*8
a=(n/r)
b=n//2
c=n**r
print(x)
print(k)
print(y)
print(z)
print(c)

[ 3  9 11 25]
[ 1  5 -1 19]
[ 4  9  7 24]
[ 16  56  40 176]
[    2    49 15625 10648]


In [27]:
p=np.array([22,33,44,55])
q=np.array([4,2,3,4])
print(p/q)
print(p//q)     # Always round down the Answer 


[ 5.5        16.5        14.66666667 13.75      ]
[ 5 16 14 13]


In [28]:
a=np.array([
    [5,10,9,8],
    [7,3,1,7]
])
b=np.array([5,6,7,8])

print(a/b)
print(b/a)

[[1.         1.66666667 1.28571429 1.        ]
 [1.4        0.5        0.14285714 0.875     ]]
[[1.         0.6        0.77777778 1.        ]
 [0.71428571 2.         7.         1.14285714]]


## Broadcasting Compatibility Table

| A        | B        | Output   | ✅/❌ | Notes |
|----------|----------|----------|------|-------|
| (n,)     | (n,)     | (n,)     | ✅    | Same shape |
| (n,)     | scalar   | (n,)     | ✅    | Scalar stretches |
| (x,n)    | (x,n)    | (x,n)    | ✅    | Same shape |
| (x,n)    | scalar   | (x,n)    | ✅    | Scalar stretches |
| (x,n)    | (n,)     | (x,n)    | ✅    | `(n,)` becomes `(1,n)` |
| (x,n)    | (1,n)    | (x,n)    | ✅    | Row stretches |
| (x,n)    | (x,1)    | (x,n)    | ✅    | Column stretches |
| (x,1)    | (1,n)    | (x,n)    | ✅    | Both stretch |
| (a,b,n)  | (a,b,n)  | (a,b,n)  | ✅    | Same shape |
| (a,b,n)  | (b,n)    | (a,b,n)  | ✅    | Depth stretches |
| (a,b,n)  | (1,b,n)  | (a,b,n)  | ✅    | Depth stretches |
| (a,b,n)  | (a,1,n)  | (a,b,n)  | ✅    | Rows stretch |
| (a,b,n)  | (a,b,1)  | (a,b,n)  | ✅    | Cols stretch |
| (a,b,n)  | (1,1,n)  | (a,b,n)  | ✅    | Both stretch |
| (a,b,n)  | (1,1,1)  | (a,b,n)  | ✅    | All stretch |
| (x,n)    | (y,n) y≠1| ❌       | ❌    | Row mismatch |
| (x,n)    | (x,m) m≠1| ❌       | ❌    | Col mismatch |
| (a,b,n)  | (c,b,n) c≠1 | ❌    | ❌    | Depth mismatch |

---

### Broadcasting Rules → Only these 7 operators:
`+` , `-` , `*` , `/` , `//` , `%` , `**`


In [29]:
import numpy as np

# ============================================================
# 1D OPERATIONS
# ============================================================

a = np.array([1, 2, 3])       # shape (3,)
b = np.array([10, 20, 30])    # shape (3,)

print("=== 1D ===")
print(a + b)    # [11, 22, 33]
print(a - b)    # [-9, -18, -27]
print(a * b)    # [10, 40, 90]
print(a / b)    # [0.1, 0.1, 0.1]
print(a // b)   # [0, 0, 0]
print(a % b)    # [1, 2, 3]
print(a ** 2)   # [1, 4, 9]




# ============================================================
# 1D BROADCASTING — scalar
# ============================================================

print("\n=== 1D + scalar ===")
print(a + 100)   # [101, 102, 103]
print(a * 2)     # [2, 4, 6]
print(a ** 3)    # [1, 8, 27]

# dry run for ** 3 :
# 1^3 = 1
# 2^3 = 8
# 3^3 = 27


# ============================================================
# 2D OPERATIONS — same shape
# ============================================================

A = np.array([[1, 2, 3],
              [4, 5, 6]])    # shape (2,3)

B = np.array([[10, 20, 30],
              [40, 50, 60]]) # shape (2,3)

print("\n=== 2D same shape ===")
print(A + B)
# [[11, 22, 33],
#  [44, 55, 66]]

print(A * B)
# [[10,  40,  90],
#  [160, 250, 360]]

# dry run for * :
# [0][0] → 1  * 10 = 10
# [0][1] → 2  * 20 = 40
# [0][2] → 3  * 30 = 90
# [1][0] → 4  * 40 = 160
# [1][1] → 5  * 50 = 250
# [1][2] → 6  * 60 = 360

print(A // B)
# [[0, 0, 0],
#  [0, 0, 0]]

# dry run for // :
# 1//10=0,  2//20=0,  3//30=0
# 4//40=0,  5//50=0,  6//60=0


# ============================================================
# 2D BROADCASTING — (2,3) + (1,3)  row stretches
# ============================================================

b_row = np.array([[10, 20, 30]])   # shape (1,3)

print("\n=== 2D + (1,3) broadcast ===")
print(A + b_row)
# b_row stretches to:
# [[10,20,30],
#  [10,20,30]]
#
# A + b_row:
# [[1+10, 2+20, 3+30],    [[11, 22, 33],
#  [4+10, 5+20, 6+30]]  =  [14, 25, 36]]

print(A % b_row)
# [[1%10, 2%20, 3%30],    [[1, 2, 3],
#  [4%10, 5%20, 6%30]]  =  [4, 5, 6]]


# ============================================================
# 2D BROADCASTING — (2,3) + (2,1)  col stretches
# ============================================================

b_col = np.array([[10],
                  [20]])           # shape (2,1)

print("\n=== 2D + (2,1) broadcast ===")
print(A + b_col)
# b_col stretches to:
# [[10,10,10],
#  [20,20,20]]
#
# A + b_col:
# [[1+10, 2+10, 3+10],    [[11, 12, 13],
#  [4+20, 5+20, 6+20]]  =  [24, 25, 26]]

print(A ** b_col)
# [[1**10, 2**10, 3**10],    [[1,    1024, 59049],
#  [4**20, 5**20, 6**20]]  =  [huge, huge, huge ]]


# ============================================================
# 2D BROADCASTING — (3,1) + (1,3)  both stretch → (3,3)
# ============================================================

col = np.array([[1],
                [2],
                [3]])              # shape (3,1)

row = np.array([[10, 20, 30]])     # shape (1,3)

print("\n=== (3,1) + (1,3) → both stretch → (3,3) ===")
print(col + row)
# col stretches →     row stretches ↓
# [[1,1,1],           [[10,20,30],
#  [2,2,2],            [10,20,30],
#  [3,3,3]]            [10,20,30]]
#
# result:
# [[11, 21, 31],
#  [12, 22, 32],
#  [13, 23, 33]]

print(col * row)
# [[1*10, 1*20, 1*30],    [[10, 20, 30],
#  [2*10, 2*20, 2*30], =   [20, 40, 60],
#  [3*10, 3*20, 3*30]]     [30, 60, 90]]


# ============================================================
# 3D OPERATIONS — same shape
# ============================================================

A3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]]])    # shape (2,2,2)

B3 = np.array([[[10, 20],
                [30, 40]],
               [[50, 60],
                [70, 80]]])  # shape (2,2,2)

print("\n=== 3D same shape ===")
print(A3 + B3)
# block 0:              block 1:
# [[1+10, 2+20],        [[5+50, 6+60],
#  [3+30, 4+40]]         [7+70, 8+80]]
#
# = [[[11,22],[33,44]], [[55,66],[77,88]]]

print(A3 * B3)
# block 0:              block 1:
# [[1*10, 2*20],        [[5*50,  6*60],
#  [3*30, 4*40]]         [7*70,  8*80]]
#
# = [[[10,40],[90,160]], [[250,360],[490,640]]]


# ============================================================
# 3D BROADCASTING — (2,2,2) + (1,2,2)  depth stretches
# ============================================================

b3 = np.array([[[10, 20],
                [30, 40]]])   # shape (1,2,2)

print("\n=== 3D + (1,2,2) → depth stretches ===")
print(A3 + b3)
# b3 stretches across depth:
# block 0 → [[10,20],[30,40]]
# block 1 → [[10,20],[30,40]]  ← same, stretched
#
# A3 + b3:
# block 0: [[1+10,2+20],[3+30,4+40]] = [[11,22],[33,44]]
# block 1: [[5+10,6+20],[7+30,8+40]] = [[15,26],[37,48]]


# ============================================================
# 3D BROADCASTING — (2,2,2) + (2,1)  → treated as (1,2,1) wait..
# (2,2,3) + (2,3)  rows of last 2 dims match
# ============================================================

A3b = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[7, 8, 9],
                 [10,11,12]]])   # shape (2,2,3)

b2 = np.array([[10, 20, 30],
               [40, 50, 60]])    # shape (2,3)

print("\n=== (2,2,3) + (2,3) → depth stretches ===")
print(A3b + b2)
# b2 stretches to both blocks:
# block 0 → [[10,20,30],[40,50,60]]
# block 1 → [[10,20,30],[40,50,60]]
#
# block 0: [[1+10,2+20,3+30],[4+40,5+50,6+60]]
#        = [[11,22,33],[44,55,66]]
#
# block 1: [[7+10,8+20,9+30],[10+40,11+50,12+60]]
#        = [[17,28,39],[50,61,72]]


# ============================================================
# 3D BROADCASTING — (2,2,2) + scalar
# ============================================================

print("\n=== 3D + scalar ===")
print(A3 + 100)
# every element + 100
# [[[101,102],[103,104]],[[105,106],[107,108]]]

print(A3 % 3)
# every element % 3
# 1%3=1, 2%3=2, 3%3=0, 4%3=1
# 5%3=2, 6%3=0, 7%3=1, 8%3=2
# [[[1,2],[0,1]],[[2,0],[1,2]]]

=== 1D ===
[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[0 0 0]
[1 2 3]
[1 4 9]

=== 1D + scalar ===
[101 102 103]
[2 4 6]
[ 1  8 27]

=== 2D same shape ===
[[11 22 33]
 [44 55 66]]
[[ 10  40  90]
 [160 250 360]]
[[0 0 0]
 [0 0 0]]

=== 2D + (1,3) broadcast ===
[[11 22 33]
 [14 25 36]]
[[1 2 3]
 [4 5 6]]

=== 2D + (2,1) broadcast ===
[[11 12 13]
 [24 25 26]]
[[               1             1024            59049]
 [   1099511627776   95367431640625 3656158440062976]]

=== (3,1) + (1,3) → both stretch → (3,3) ===
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]

=== 3D same shape ===
[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
[[[ 10  40]
  [ 90 160]]

 [[250 360]
  [490 640]]]

=== 3D + (1,2,2) → depth stretches ===
[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]

=== (2,2,3) + (2,3) → depth stretches ===
[[[11 22 33]
  [44 55 66]]

 [[17 28 39]
  [50 61 72]]]

=== 3D + scalar ===
[[[101 102]
  [103 104]]

 [[105 106]
  [107 108]]]
[[[1 2]
  [0 1]]

 [[2 0]
  [1

## MATH FUNCTION 

In [30]:
n=np.array([16,25])
m=np.array([
    [4,225,49,84,9],
    [8,2,3,0,8]
])
p=np.array([
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
],    
[
    [2,8,9],
    [1,7,9],
    [6,7,4],
    [8,2,6]
],
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
]


])
print(np.sqrt(n))
print(np.sqrt(m))
print(np.sqrt(p))

[4. 5.]
[[ 2.         15.          7.          9.16515139  3.        ]
 [ 2.82842712  1.41421356  1.73205081  0.          2.82842712]]
[[[1.         2.64575131 3.        ]
  [0.         2.64575131 2.        ]
  [2.82842712 1.41421356 2.44948974]
  [2.44948974 2.64575131 2.        ]]

 [[1.41421356 2.82842712 3.        ]
  [1.         2.64575131 3.        ]
  [2.44948974 2.64575131 2.        ]
  [2.82842712 1.41421356 2.44948974]]

 [[1.         2.64575131 3.        ]
  [0.         2.64575131 2.        ]
  [2.82842712 1.41421356 2.44948974]
  [2.44948974 2.64575131 2.        ]]]


In [31]:
b=np.array([2,3,4])
#  [e^2,e^3,e^4]

print(np.exp(b))

[ 7.3890561  20.08553692 54.59815003]


In [32]:
#log functions & absolute function 
v=np.array([2,4,10,20])
print(np.log(v))
print(np.log2(v))
print(np.log10(v))

print(np.abs([4,5,-8,-9]))   # convert all element in positive 

[0.69314718 1.38629436 2.30258509 2.99573227]
[1.         2.         3.32192809 4.32192809]
[0.30103    0.60205999 1.         1.30103   ]
[4 5 8 9]


In [33]:
# np.ceil()   np.floor()   np.round()   Rounding functions
a=np.array( [1.2, 1.49,1.54, -1.7, 2.9])
print(np.ceil(a))           # Round up to every element 
print(np.floor(a))          # Round up to every element 
print(np.round(a))          #  (below .5 → go down) 
                            #  (.5 and above → go up)

[ 2.  2.  2. -1.  3.]
[ 1.  1.  1. -2.  2.]
[ 1.  1.  2. -2.  3.]


## Matrics Functions 
1. **np.dot()** ,  **@** and **np.matmul()** are same for 2d array  

- For 2D matrices → @, matmul, dot → same output.

- For 1D vectors →  only dot() works (inner product), but @ and matmul throw value error.

- For higher dimensions (>2D) → dot behaves differently (contracts axes), while @ and matmul do batch matrix multiplication.

In [48]:
# If both inputs are 1D vectors (n,), np.dot() gives a scalar (inner product).
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
# print(a @ b)
# print(np.dot(a,b))

x=np.array([
    [4,5,1],
    [6,2,7],
    [5,1,8]
])
y=np.array([
    [3],
    [4],
    [2]
])    # Acts like a column vector in dot products.
z=np.array([[3,6,4]])
print(x @ y)
print(y @ z)
# print(x @ y)
# print(np.dot(x ,y))





[[34]
 [40]
 [35]]
[[ 9 18 12]
 [12 24 16]
 [ 6 12  8]]


In [49]:
p=np.array([
    [6,2],
    [4,1],
    [6,2]
])
q=np.array([
    [8,2,2],
    [5,4,6]
    

])
print(np.dot(p,q))
print(p @ q)
print(np.matmul(p,q))

[[58 20 24]
 [37 12 14]
 [58 20 24]]
[[58 20 24]
 [37 12 14]
 [58 20 24]]
[[58 20 24]
 [37 12 14]
 [58 20 24]]


In [50]:

X = np.ones((2,2,3))   
Y = np.ones((2,3,4)) 
print(X @ Y,"\n")
print((X @ Y).shape)
print(np.matmul(X,Y).shape)
print(np.dot(X,Y).shape)

[[[3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]]] 

(2, 2, 4)
(2, 2, 4)
(2, 2, 2, 4)


**np.cross()**
- np.cross() → needs vectors of length 2 or 3
- for 2D arrays, operates row‑wise. it works row by row (each row treated as a vector).
- use (i,j,k) as column indexes 

In [51]:

#  1D Vector :
# give a cross multiplication between 2 vector

import numpy as np

a = np.array([1, 2, 3])   
b = np.array([4, 5, 6])   

print(np.cross(a, b))



[-3  6 -3]


In [ ]:
# 2D Array :
# cross product between  first row of both vector 
A = np.array([[1,2,3],
              [4,5,6]])   # shape (2,3)

B = np.array([[7,8,9],
              [1,0,0]])   # shape (2,3)

print(np.cross(A, B))


[[-6 12 -6]
 [ 0  6 -5]]


**np.outer()**<br>
<b>np.outer() → always flattens inputs to 1D, then builds a multiplication table.</b>
- Works on 1D arrays only.

- If you pass higher‑dimensional arrays, they get flattened first.

- Result shape = (len(a), len(b)).

In [61]:
a=np.array([
    [6,3,4],          # convert in into flattened (1d) array 
    [9,6,7],          # use x.flatten()
    [1,2,4]
])
b=np.array([5,6,7])
#  Resultant Array's shape : (len(a) ,len(b))
print(np.outer(a,b))

[[30 36 42]
 [15 18 21]
 [20 24 28]
 [45 54 63]
 [30 36 42]
 [35 42 49]
 [ 5  6  7]
 [10 12 14]
 [20 24 28]]
