CH 4
Indexing & Slicing 

In [3]:
import numpy as np
b=np.array([4,5,2,7,8,9,1,0])
x=print(b.size)
print(b[0],b[-8])
print(b[5])

8
4 4
9


In [4]:
#  slicing 
b=np.array([1,4,5,2,7,9,0,8,8,7,6,2,3,4,5])
print(b.size)
print(b[0:15:2])                       # [start : stop(execluding) : step]

15
[1 5 7 0 8 6 3 5]


In [5]:
# 2d array indexing and slicing 

c=np.array([
    [5,6,45],
    [63,3,4],
    [1,8,5]


])
# how to slice any raw :  arr[raw, :]
print(c[1,:])
# how to slice any cloumn  arr[:, col]
print(c[:,2])
# sub matircs slice  arr[r1:r2, c1:c2]
print(c[0:2,0:2])

[63  3  4]
[45  4  5]
[[ 5  6]
 [63  3]]


In [6]:
o=np.array([
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
],    
[
    [2,8,9],
    [1,7,9],
    [6,7,4],
    [8,2,6]
],
[
    [18,7,56],
    [6,8,0],
    [0,2,5],
    [8,9,0]
]


])

print(o[0,0,0:2])
print(o[0])        # 0th element of 3d array is 1st layer 
print(o[2])        # 1st element of 3d array is 2d layer 
print(o[0,0:2])    # Go through the 0th element(1st) array and raw is act as one element  
print()


[1 7]
[[1 7 9]
 [0 7 4]
 [8 2 6]
 [6 7 4]]
[[18  7 56]
 [ 6  8  0]
 [ 0  2  5]
 [ 8  9  0]]
[[1 7 9]
 [0 7 4]]



Negative indexing in 2D
arr[-1, :] / arr[:, -1]


In [7]:
g=np.array([
    [1,3,5,6],
    [7,8,7,4],
    [5,6,2,1],
    [9,0,1,5]
])
print(g[-1,:])
print(g[-3,:])
print(g[:,-1])
print(g[:,-4])

[9 0 1 5]
[7 8 7 4]
[6 4 1 5]
[1 7 5 9]


3D Array Indexing & Slicing

In [8]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],    # Layer 1

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]], # Layer 2

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]  # Layer 3
])
# arr[layer]
# One full 2D layer 
print(arr[2])
print("Only Layer  : " )
print(arr[2,:,:])
print("Only Row  : " )
print(arr[:,2,:])
print("Only Column  : " )
print(arr[:,:,[2]])

# arr[l, r, c]
# Lth layer ,Rth raw , and Cth column

print(arr[2,1,1])

[[19 20 21]
 [22 23 24]
 [25 26 27]]
Only Layer  : 
[[19 20 21]
 [22 23 24]
 [25 26 27]]
Only Row  : 
[[ 7  8  9]
 [16 17 18]
 [25 26 27]]
Only Column  : 
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]
23


3D CUBE Slicing 
arr[l1:l2, r1:r2, c1:c2]   


In [9]:
print(arr[0:3, 0:2, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


Array Operation & Math 
# ⚡ Conditions for Array Operations in NumPy

## 1. Same Shape
- Arrays must have the **same shape** for direct element‑wise operations.
- Example: `(2,3)` + `(2,3)` → works ✔

---

## 2. Broadcasting Rule
- If shapes differ, NumPy applies **broadcasting**.
- Rule: Compare dimensions **from right to left**.
  - Two dimensions are compatible if:
    - They are **equal**, OR
    - One of them is **1** (can be stretched).
- If all dimensions follow this → operation works ✔
- If not → ❌ `ValueError`

---

## 3. Scalar with Array
- A single number (scalar) always works with any array.
- Example: `arr + 5` → adds 5 to every element ✔

---

## 4. Incompatible Shapes
- If dimensions are neither equal nor 1 → operation fails.
- Example: `(2,3)` + `(2,)` → ❌ error (last dim 3 vs 2)

---

In [26]:
n=np.array([2,7,6,22])
r=np.array([1,2,5,3])
x=n+r
y=n+2
z=n*8
a=(n/r)
b=n//2
c=n**r
print(x)
print(y)
print(z)
print(c)

[ 3  9 11 25]
[ 4  9  8 24]
[ 16  56  48 176]
[    2    49  7776 10648]
