## CH6 Aggregation & Statistics Must learn
**1)  BASIC STATS**

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 =  np.array([[1, 2, 3],
                  [4, 5, 6]
                  ])
print("For arr1 ------>")
print("Sum      : ", np.sum(arr1) )
print("Mean     : ", np.mean(arr1))
print("Median   : ", np.median(arr1))
print("Minimun  : ", np.min(arr1))
print("Maximum  : ", np.max(arr1))


For arr1 ------>
Sum      :  15
Mean     :  3.0
Median   :  3.0
Minimun  :  1
Maximum  :  5


**Standard Deviation (𝜎) *std()* and Variance (𝜎^2)**

In [2]:
print(np.std(arr1))
print(np.var(arr1))
a1=np.array([
 [ 1, 2, 3, 4, 5, 6, 7],
 [ 8, 9,10,11,12,13,14],
 [15,16,17,18,19,20,21],
 [22,23,24,25,26,27,28],
 [29,30,31,32,33,34,35],
 [36,37,38,39,40,41,42],
 [43,44,45,46,47,48,49]
 
 ])
#  case 1: whole Array : 

print(np.std(a1))
print(np.var(a1))

#  case 2 : column wise :
# All column's treated as one dimensional data
print(np.var(a1, axis=0), np.std(a1, axis=0))

#  case 3 : row wise :
#  All rows treated as one dimensional data
print(np.var(a1, axis=1), np.std(a1, axis=1))


1.4142135623730951
2.0
14.142135623730951
200.0
[196. 196. 196. 196. 196. 196. 196.] [14. 14. 14. 14. 14. 14. 14.]
[4. 4. 4. 4. 4. 4. 4.] [2. 2. 2. 2. 2. 2. 2.]


**2) Advance**

In [3]:
# np.percentile()
# Finds the value at a given percentile (0–100).
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
print(np.percentile(a, 50))   # median
print(np.percentile(a, 25))   # 25th percentile

# np.quantile()
# Similar to percentile, but uses fraction (0–1).
print(np.quantile(a,0.3))
print(np.quantile(a,0.7))

45.0
27.5
31.0
58.99999999999999


In [4]:
c=np.array([7,3,6,2,8,4,5])
d=np.array([1,2,1,2,1,2,1])
print(np.average(c))
print(np.average(c,weights=d))
e=np.array([
    [3, 4, 2, 3],
    [9, 0, 1, 5],
    [5,-2, 4, 3]
])
#  flattens the array first 
print(np.average(e))
print(np.average(e,axis=1))     # Column wise - average
print(np.average(e,axis=0))     # row wise - average 
print(np.average(e,axis=-1))    # last dimension or last low 

5.0
4.4
3.0833333333333335
[3.   3.75 2.5 ]
[5.66666667 0.66666667 2.33333333 3.66666667]
[3.   3.75 2.5 ]


In [5]:
#  np.corrcoef(x, y=None, rowvar=True)
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8])
exam_scores = np.array([50, 55, 60, 65, 70, 75, 80, 85])
random_data = np.array([30, 80, 10, 90, 20, 70, 50, 40])

corr_positive = np.corrcoef(study_hours, exam_scores)
corr_random   = np.corrcoef(study_hours, random_data)
print(corr_positive,"\n", corr_random)

[[1. 1.]
 [1. 1.]] 
 [[1.         0.03016485]
 [0.03016485 1.        ]]


## `np.cov()` — Covariance Matrix

### What it does?
Measures **how much two variables change together** (actual scale, not normalized)
- Interpret off-diagonal value

| Value   | Meaning                        |
|---------|--------------------------------|
| cov > 0 | both increase together         |
| cov < 0 | one increases, other decreases |
| cov = 0 | no linear relationship         |


In [6]:
# For 1D Array:
#  single value (variance of x itself)
# variance = how much x deviates from its own mean
        #  = Σ(xi - x̄)² / (n-1)
d1=np.array([3,6,4,2,1,7,8])
print(np.cov(d1))

#  For 2D Array:
# cov(x,y) = Σ(xi - x̄)(yi - ȳ) / (n-1)

#  np.cov returns : 
        # x       y
# x  [ var(x),  cov(x,y) ]     [ 2.5,  5.0 ]
# y  [ cov(y,x), var(y)  ]  

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.cov(x, y))


6.9523809523809526
[[ 2.5  5. ]
 [ 5.  10. ]]


##  Cumulative fucntions
Always Return 1D Result(when axis parameter is not passed )
- np.cumsum()   # each element = sum of all previous + itself
- np.cumprod()  # each element = product of all previous + itself

In [7]:
c=np.array([4,   5,     3,       2,          1])
#           4    4+5   4+5+3    4+5+3+2   4+5+3+2+1
print(np.cumsum(c))
print(np.cumprod(c))
d=np.array([
    [4,5,7,2,3,1],
    [6,7,3,5,2,9],
    [4,5,3,2,1,5]
])
#  for 2d array first convert it into flattened
print(np.cumsum(d),"\n")
print("column wise cumsum:\n",np.cumsum(d,axis=0),"\n")
print("Row wise cumsum:\n",np.cumsum(d,axis=1),"\n")
print(np.cumprod(d),"\n")

[ 4  9 12 14 15]
[  4  20  60 120 120]
[ 4  9 16 18 21 22 28 35 38 43 45 54 58 63 66 68 69 74] 

column wise cumsum:
 [[ 4  5  7  2  3  1]
 [10 12 10  7  5 10]
 [14 17 13  9  6 15]] 

Row wise cumsum:
 [[ 4  9 16 18 21 22]
 [ 6 13 16 21 23 32]
 [ 4  9 12 14 15 20]] 

[         4         20        140        280        840        840
       5040      35280     105840     529200    1058400    9525600
   38102400  190512000  571536000 1143072000 1143072000 5715360000] 



## Axis Summary Table

| axis | direction | works on |
|------|-----------|----------|
| `axis=0` | top → bottom ↓ | each column |
| `axis=1` | left → right → | each row |
| `axis=-1` | last dimension | same as highest axis |
| `None` | row by row (C-order) | returns 1D result |

In [8]:
print()
e=np.array([
    [4,5,7,2,3,1],
    [6,7,3,5,2,9],
    [4,5,3,2,1,5]
])
print(np.sum(e,axis=0))
print(np.var(e,axis=-1))


[14 17 13  9  6 15]
[3.88888889 5.55555556 2.22222222]


In [9]:
d = np.array([[4,5,7],
              [6,7,3]])

# 2D has only 2 axes → axis 0 and axis 1
# axis=-1 == axis=1  (last dim)
# axis=-2 == axis=0  (second last dim)

print(np.cumsum(d, axis=-1))  # same as axis=1
print(np.cumsum(d, axis=-2))  # same as axis=0

[[ 4  9 16]
 [ 6 13 16]]
[[ 4  5  7]
 [10 12 10]]


In [10]:
arr = np.array([[[1,2,3],
                 [4,5,6]],
                [[7,8,9],
                 [1,2,3]]])

# shape → (2, 2, 3)
#          ↑  ↑  ↑
#        ax0 ax1 ax2
#        ax-3 ax-2 ax-1

print(np.sum(arr,axis=1))
print(np.sum(arr,axis=-1))

[[ 5  7  9]
 [ 8 10 12]]
[[ 6 15]
 [24  6]]


## Shape manipulation 

In [11]:
#  reshape()
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)   # 1D → 2D
arr.reshape(2,3,1) # 1D → 3D
arr.reshape(-1).shape    # any → 1D (auto calculate)
arr.reshape(-1,1)  # any → column vector
arr.reshape(1,-1)  # any → row vector

# -1 means → let numpy calculate that dimension automatically
#  we can fix one desired dimesntion and other numpy will calculate it self automaticall
# ONLY RULE : Total elements must stay same 
# ML use → convert 1D feature vector to 2D for model input


array([[1, 2, 3, 4, 5, 6]])

In [12]:
# flatten()
#  Result Shape Always (n,)
n=np.array([3,4])
m=np.array([
    [4,5,7,8,9],
    [8,2,3,0,8]
])
o=np.array([
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
],    
[
    [2,8,9],
    [1,7,9],
    [6,7,4],
    [8,2,6]
],
[
    [1,7,9],
    [0,7,4],
    [8,2,6],
    [6,7,4]
]


])
print(n.flatten())
print(m.flatten())
print(m.flatten('C'))     # row by row (default)
print(m.flatten('F'))     # column by column
print(o.flatten())

# ML use → flatten image (28×28) → 1D (784,) for dense layer input

[3 4]
[4 5 7 8 9 8 2 3 0 8]
[4 5 7 8 9 8 2 3 0 8]
[4 8 5 2 7 3 8 0 9 8]
[1 7 9 0 7 4 8 2 6 6 7 4 2 8 9 1 7 9 6 7 4 8 2 6 1 7 9 0 7 4 8 2 6 6 7 4]


In [13]:
vrr=np.array([5,3,5,2,5,6,7,9])
# returns VIEW (not copy!)
print(vrr.ravel('C'))    # row by row (default)
print(vrr.ravel('F'))    # column by column

[5 3 5 2 5 6 7 9]
[5 3 5 2 5 6 7 9]


In [14]:
print(o.shape)
print(o.transpose(1,0,2))
# 0 --> layer
# 1 --> row
# 2 --> column 
r=np.array([
    [6,3,2,4],
    [6,2,4,8]
    ])
print(r.shape)
print((r.T).shape)
# ML use → weight matrix operations, attention mechanism in transformers

(3, 4, 3)
[[[1 7 9]
  [2 8 9]
  [1 7 9]]

 [[0 7 4]
  [1 7 9]
  [0 7 4]]

 [[8 2 6]
  [6 7 4]
  [8 2 6]]

 [[6 7 4]
  [8 2 6]
  [6 7 4]]]
(2, 4)
(4, 2)


**EXPAND / SQUEEZE functions**

In [15]:
# expand_dims adds a dimension to match model's expected
#  input shape, squeeze removes unwanted size-1 dimensions
#  from model output — they exist to handle batch dimension
#  requirements in ML pipelines."


In [16]:
import numpy as np

a = np.array([1,2,3])

print(a.ndim)
b=np.expand_dims(a,axis=0)
c=np.expand_dims(a,axis=1)
print(b.ndim,b.shape,"\n",b)
print(c.ndim,c.shape,"\n",c)



1
2 (1, 3) 
 [[1 2 3]]
2 (3, 1) 
 [[1]
 [2]
 [3]]


In [17]:
g=np.array([[5,6,7]])
print(g.shape)
b = np.squeeze(g)

print(b)
print(b.shape)

(1, 3)
[5 6 7]
(3,)


- **concatenate()** → Joins arrays along an existing axis without increasing dimension.
- **stack()** → Joins arrays by creating a new dimension (new axis).

In [18]:
# Concantenate
r=np.array([[5,3,8,9,0]])
s=np.array([[3,4,2,6,4]])
t=np.concatenate((r,s),axis=0)
u=np.concatenate((r,s),axis=1)
print(t)
print(u)

a = np.array([
 [1,2],
 [3,4]
])

b = np.array([
 [5,6],
 [7,8]
])
t=np.concatenate((a,b),axis=0)
u=np.concatenate((a,b),axis=1)
print(t)
print(u)


[[5 3 8 9 0]
 [3 4 2 6 4]]
[[5 3 8 9 0 3 4 2 6 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [19]:
a = np.array([
 [1,2],
 [3,4]
])

b = np.array([
 [5,6],
 [7,8]
])
t=np.stack((a,b),axis=0)


print(u)

[[1 2 5 6]
 [3 4 7 8]]


- **np.hstack()** → Horizontal Stack
- **np.vstack()** → Vertical Stack
- **np.dstack()** → Depth Stack (Stacks along 3rd dimension.)

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

s=np.hstack([a,b])   # horizontal → [1,2,3,4,5,6]       axis=1
r=np.vstack([a,b])   # vertical   → [[1,2,3],[4,5,6]]    axis=0
b=np.dstack([a,b])   # depth      → [[[1,4],[2,5],[3,6]]] axis=2
print(s,"dimension : ",s.ndim)
print(r,"dimension : ",r.ndim)
print(b,"dimension : ",b.ndim)

[1 2 3 4 5 6] dimension :  1
[[1 2 3]
 [4 5 6]] dimension :  2
[[[1 4]
  [2 5]
  [3 6]]] dimension :  3


In [31]:
# np.split(arr, number of parts, axis=) → Split Array

f=np.array([
    [6,7,5],
    [3,2,1],
    [5,4,5]
])
print(np.split(f,3))
h=np.ones((1,5))
print(np.split(h,5,axis=1))



[array([[6, 7, 5]]), array([[3, 2, 1]]), array([[5, 4, 5]])]
[array([[1.]]), array([[1.]]), array([[1.]]), array([[1.]]), array([[1.]])]



- split()        ->	    **General cut**
- hsplit()       ->	    **Cut columns**
- vsplit()       ->	    **Cut rows**
- split()        ->     **Cut depth**
- array_split()  ->	    **Flexible cut**

In [32]:
a = np.array([
 [1,2,3,4],
 [5,6,7,8]
])

print(a)
print(a.shape)
print(np.split(a,2))
print(np.hsplit(a,2))
print(np.vsplit(a,2))
b = np.array([1,2,3,4,5])

print(np.array_split(b,3))
c = a.reshape(2,2,2)

print(c)
print(c.shape)
print(np.dsplit(c,2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([1, 2]), array([3, 4]), array([5])]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [37]:
# np.tile() → Repeat Whole Pattern
# np.repeat() → Repeat Elements
v=np.array([6,7,6,9])
print(np.tile(v,4))
print(np.repeat(v,3))

[6 7 6 9 6 7 6 9 6 7 6 9 6 7 6 9]
[6 6 6 7 7 7 6 6 6 9 9 9]
