- Boolean Indexing & Filtering | Broadcasting | Sorting & Searching

In [47]:
import numpy as np

arr=np.array([1, 3, 5, 7, 2, 6, 8, 4, 6])
# Return Array elements which is bigger than 5
print(arr[arr>5])
#  Return Array elements which is equal to 6
print(arr[arr==6])
# Indexing with conditions 
# multiple conditions using & (and) | (or)
print(arr[(arr>0) & (arr<6)])



[7 6 8 6]
[6 6]
[1 3 5 2 4]


- np.where()
`np.where(condition, value_if_true, value_if_false)` <br>— works like if-else on entire array at once.

In [48]:
arr = np.array([1, 3, 5, 7, 2, 8, 4, 6])

# replace values — if > 5 put -->  1
#                    else put -->  0
print(np.where(arr > 5, 1, 0))
# if u need to remains value same so put "arr" instead of 1 as parameter 

# get indices where condition is true
# returns tuple — use [0] to get array of indices
print((np.where(arr > 5)[0]))

# real use of np.where
marks=np.array([50,44,80,55,42,67,78,36])
result=np.where(marks >50,"pass","fail")
print(result)


[0 0 0 1 0 1 0 1]
[3 5 7]
['fail' 'fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'fail']


- np.any() and np.all() (output= `boolean`) <br> 
`any()` returns True if at least one element satisfies condition.<br> `all()` returns True only if every element satisfies condition.

In [49]:
arr2 = np.array([1, 3, 5, 7, 2, 8, 4, 6])

# any — is there at least one element > 7
print(np.any(arr2 > 7))    # True  (8 exists)

# all — are ALL elements > 0
print(np.all(arr2 > 0))    # True  (all positive)

# all — are ALL elements > 5
print(np.all(arr2 > 5))    # False (1,3,2,4 are not)
# with axis — check row/column wise in 2D
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.any(mat > 5, axis=1))   # check each row
print(np.any(mat > 5, axis=0))   # check each column


True
True
False
[False  True]
[False False  True]


- **NaN**   <br>
 Handling Real world data often has **missing values** stored as **NaN**. These 4 functions help **detect and clean them**.

In [50]:
arr = np.array([1.0, np.nan, 3.0, np.inf, -np.inf, 5.0])

# np.isnan — find NaN values (not a number)
print(np.isnan(arr))        # True where NaN

# np.isinf — find infinite values
print(np.isinf(arr))        # True where inf or -inf

# np.isfinite — find normal finite values only
print(np.isfinite(arr))     # True where normal number

# np.nan_to_num — replace NaN and inf with numbers
# nan → 0,  inf → large number,  -inf → large negative
print(np.nan_to_num(arr))

# custom replacement — replace nan with 0, inf with 99
print(np.nan_to_num(arr,nan=0,posinf=99,neginf=-99))


[False  True False False False False]
[False False False  True  True False]
[ True False  True False False  True]
[ 1.00000000e+000  0.00000000e+000  3.00000000e+000  1.79769313e+308
 -1.79769313e+308  5.00000000e+000]
[  1.   0.   3.  99. -99.   5.]


- **Broadcasting**<br>
Broadcasting allows numpy to perform operations on arrays of different shapes without copying data.<br><br>
 **Shape Alignment Rules**<br>
Numpy compares shapes from right to left. Dimensions are compatible if they are equal or one of them is 1.

In [51]:
# rule — compare shapes right to left
# (3,)  and  (3,)   → equal        → compatible
# (1,)  and  (3,)   → one is 1     → compatible (stretches)
# (2,)  and  (3,)   → neither 1    → ERROR

a = np.array([1, 2, 3])      # shape (3,)
b = np.array([10])            # shape (1,) — will stretch

print(a + b)    # [11, 12, 13]  b stretched to match a

[11 12 13]


- Practical Use — **Adding Bias Term**
In neural networks bias is added to every row of the output — broadcasting handles this automatically.

In [52]:
# neuron outputs — 3 samples, 4 features each
output = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9,10,11,12]])   # shape (3,4)

bias = np.array([0.1, 0.2, 0.3, 0.4])   # shape (4,)

# bias added to every row automatically
print(output + bias)   # shape stays (3,4)

[[ 1.1  2.2  3.3  4.4]
 [ 5.1  6.2  7.3  8.4]
 [ 9.1 10.2 11.3 12.4]]


## 9. Broadcasting (Most Important in ML)
- (Small thoery )
## Broadcasting means:
NumPy automatically adjusts shapes so arrays can perform operations together.  
Instead of manually copying data, NumPy stretches smaller arrays virtually.

---

## Why Broadcasting Needed?
Without broadcasting:
- many loops required  
- code becomes slow  
- ML frameworks become inefficient  

---

## ML Frameworks
TensorFlow/PyTorch heavily use broadcasting internally.

- Broadcasting Rules (Core Concept)<br>

`Rule 1`: Compare Shapes From Right Side

Example:
(3,4)
(4)

Compare from right:

(3,4)
(  4)

4 == 4 ✅

So operation possible.

`Rule 2`: Dimensions Compatible If<br>

-> A dimension is compatible when:

both equal
OR
one of them is 1

Example:

(3,4)
(1,4)

Compatible because:

4 == 4<br>
1 can stretch to 3Rule 2: Dimensions Compatible If

A dimension is compatible when:

both equal
OR
one of them is 1

Example:

(3,4)
(1,4)

Compatible because:

4 == 4<br>
1 can stretch to 3

`Rule 3`: Missing Dimension Treated as 1

Example:

(5,)

treated like : (1,5)

Rank Stretching

Rank = number of dimensions.

Example:

[1,2,3]

Shape : (3,)

Rank = 1

Now:

[[1,2,3],<br>
 [4,5,6]]

Shape : (2,3)

Rank = 2

NumPy stretches lower-rank arrays automatically.<br>

**Automatic Expansion**

Example:

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

Dry Run:

a shape = (2,3)
b shape = (3,)

NumPy imagines:

[[10,20,30],<br>
 [10,20,30]]

Result:

[[11 22 33]<br>
 [14 25 36]]<br><br>
**Broadcasting Visualization**
(2,3)
(3,)

Internally becomes:

(2,3)
(1,3)

then stretches:

(2,3)
(2,3)



<h2>10. Sorting & Searching</h2>

- `np.sort()`
Sorts values.

- `np.argsort()`
Returns indices of sorted order.

In [53]:
ar=np.array([10,40,55,15,60])
print(np.sort(ar))
print("Indices ",np.argsort(ar))

mt=np.array([
    [6,7,3],
    [5,-2,6],
    [0,-5,9]
])
print(np.sort(mt))     # here by default axis = 1 parameter is passed  and each row of "mt" is sorted 
print("Indices\n",np.argsort(mt))   

[10 15 40 55 60]
Indices  [0 3 1 2 4]
[[ 3  6  7]
 [-2  5  6]
 [-5  0  9]]
Indices
 [[2 0 1]
 [1 0 2]
 [1 0 2]]


In [54]:
name = np.array(['A','B','C'])
marks = np.array([90,70,90])

print(np.lexsort((name, marks)))

[1 0 2]


In [55]:
#  argmin() and argmax()
# return the index of max and min element
arr2=np.array([20,50,5,6,24,89,445,6654])
print(np.argmax(arr2))
print(np.argmin(arr2))

mat1=np.array([
    [5,-6,8,5],
    [3,12,45,65],
    [4,-8,5,6],
    [10,23,-4,7]
])
# column wise 
print(np.argmax(mat1,axis=0))
print(np.argmin(mat1,axis=0))


7
2
[3 3 1 1]
[1 2 3 0]


## 10. Sorting & Searching
 `np.sort()` :
Returns sorted copy of array. Original stays unchanged.<br>
 `np.argsort()`:
Returns indices that would sort the array — very useful when you need to reorder other arrays by same order.

In [56]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# default ascending order
print(np.sort(arr))

# descending — sort then reverse
print(np.sort(arr)[::-1])

# 2D sort
mat = np.array([[3,5,2],
                [9,1,7]])
print(np.sort(mat))
print("Indices :\n",np.argsort(mat))     # Return Indices  
print("Row and column wise : \n")
print(np.sort(mat, axis=0))   # sort each column
print(np.sort(mat, axis=1))   # sort each row

[1 1 2 3 4 5 6 9]
[9 6 5 4 3 2 1 1]
[[2 3 5]
 [1 7 9]]
Indices :
 [[2 0 1]
 [1 2 0]]
Row and column wise : 

[[3 1 2]
 [9 5 7]]
[[2 3 5]
 [1 7 9]]


In [57]:
#  uses of
scores = np.array([100, 85, 71, 63, 62])
names  = np.array(["Tendulkar","Kohli","Ponting","Sangakkara","Kallis"])

# get indices that would sort scores
idx = np.argsort(scores)
print(idx)              # [3,1,4,0,2]

# use same indices to sort names by score
print(scores[idx])      # sorted scores
print(names[idx])       # names in order of score

# descending — reverse the indices
print(names[idx[::-1]])

[4 3 2 1 0]
[ 62  63  71  85 100]
['Kallis' 'Sangakkara' 'Ponting' 'Kohli' 'Tendulkar']
['Tendulkar' 'Kohli' 'Ponting' 'Sangakkara' 'Kallis']


- `np.lexsort`() :
Sort using multiple keys.

In [58]:
scores = np.array([100, 85, 71, 63, 62])
names  = np.array(["Tendulkar","Kohli","Ponting","Sangakkara","Kallis"])

# note — last key is primary sort key
idx = np.lexsort((names, scores))   # primary=scores, secondary=names
print(scores[idx])
print(names[idx])

[ 62  63  71  85 100]
['Kallis' 'Sangakkara' 'Ponting' 'Kohli' 'Tendulkar']


`np.argmin()` and `np.argmax()`:<br>
Return the index of minimum and maximum value — used in every classifier to get predicted class.

In [59]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(np.argmin(arr))   # index of smallest value
print(np.argmax(arr))   # index of largest value

# ML use — model outputs probability for each class
probabilities = np.array([0.05, 0.10, 0.75, 0.08, 0.02])
predicted_class = np.argmax(probabilities)
print('predicted class:', predicted_class)   # 2

# 2D — axis wise
mat = np.array([[3,1,4],
                [9,2,7]])
print(np.argmax(mat, axis=0))   # index of max in each column
print(np.argmax(mat, axis=1))   # index of max in each row

1
5
predicted class: 2
[1 1 1]
[2 0]


`np.searchsorted()`:<br>
Finds index where a value should be inserted to keep array sorted — uses binary search internally.<br>
Basic : 
np.searchsorted(arr, value, side='left')

In [60]:
# array must be sorted first
arr = np.array([10, 20, 30, 40, 50])

# where should 25 be inserted to keep sorted order
print(np.searchsorted(arr, 25))       # 2 (between 20 and 30)

# side='right' — insert after existing equal values
print(np.searchsorted(arr, 30, side='left'))   # 2
print(np.searchsorted(arr, 30, side='right'))  # 3

# search multiple values at once
print(np.searchsorted(arr, [15, 35, 55]))

2
2
3
[1 3 5]


 `np.nonzero()` : <br>
Returns indices of all non-zero elements — useful for finding where conditions are True.

In [70]:
arr = np.array([0, 3, 0, 0, 5, 0, 2])

# returns tuple of arrays — one array per dimension
print(np.nonzero(arr))       # (array([1, 4, 6]),)
print(np.nonzero(arr)[0])    # [1, 4, 6]  just the indices

# use with boolean condition
scores = np.array([45, 78, 90, 33, 65])
print(np.nonzero(scores > 60)[0])   # indices where score > 60

(array([1, 4, 6]),)
[1 4 6]
[1 2 4]


`np.unique() `:<br>
Returns sorted unique elements. With `return_counts=True` also returns how many times each appeared.

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# just unique values
print(np.unique(arr))

# unique values with their counts
values, counts = np.unique(arr, return_counts=True)
print(values)    # unique elements
print(counts)    # how many times each appeared

# ML use — check class distribution in labels
labels = np.array([0, 1, 0, 2, 1, 0, 1, 2, 0])
classes, freq = np.unique(labels, return_counts=True)
for c, f in zip(classes, freq):
    print(f'class {c} : {f} samples')
    

[1 2 3 4 5 6 9]
[1 2 3 4 5 6 9]
[2 1 2 1 3 1 1]
class 0 : 4 samples
class 1 : 3 samples
class 2 : 2 samples
